# Uncomment this line to define a global platform for your project
use_frameworks!
platform :ios, '8.0'

target 'KGFloatingDrawer-Example' do
  pod 'KGFloatingDrawer', :git => 'https://github.com/KyleGoddard/KGFloatingDrawer.git', :tag => '0.1.2'
end

target 'KGFloatingDrawer-ExampleTests' do

end
