# Uncomment this line to define a global platform for your project
use_frameworks!
platform :ios, '8.0'

target 'KGFloatingDrawer-Example' do
  pod 'KGFloatingDrawer', :path => "../"
end

target 'KGFloatingDrawer-ExampleTests' do

end
